### ISSUE TITLE
tftp_client::upload() function returns error "Timeout while trying to complete action"

### ISSUE THREAD

**Issue by dboycepa** [kiranshila/tftp_client#1]
Context: trying to upload a file via the tftp_client::upload() function in crate version 0.1.0 over a socket to a standard in.tftpd server (for demo purposes, listening on address 127.0.0.1:69)

Using wireshark to analyse what's happening, the ACK responses are being ignored; these come from a different src port and are being ignored by the connected tftp_client socket, which can only receive packets from the port to which it connected (i.e. 69).

In this case, we reach the maximum timeout and the Error::Timeout is returned.

With a different tftpd server implementation, I've seen it fail with "The protocol itself gave us an error with code `Unspec` and msg `BUSY`", which is how I know it's receiving messages from the original connection port.  In this case, the initial timeout causes the WriteRequest to be re-sent; the server appears to regard the re-send of the block 0 WriteRequest packet as a request to initiate another write and says "Nah, I'm busy".

At the root of this is the passing in of a connected socket, which prevents the socket receiving any response sent from another port.  The upload socket must be connectionless, which means an additional SocketAddr address is needed (or perhaps replace the passed-in socket argument).

Edit: add context.

**Comment by kiranshila** [comment]
Hmm interesting. Can you provide an example (and which server you're using)?

**Comment by dboycepa** [comment]
My server is the standard in.tftpd, run as follows on Centos Stream 8:

`sudo in.tftpd -L --create -s /tmp/tftpd_output`

For and example, create a crate whose main.rs is the content of your existing example/upload.rs, and modify:

1. the connect address string to something appropriate (I run this demo on the same machine, so use "127.0.0.1:69");
2. the filename to its basename (e.g. "spec_a_vacc")

(2) is a consequence of using the -s flag on in.tftpd

Build and run the example crate

```
$ cargo build
    Updating crates.io index
[snipped]
   Compiling tftp_client v0.1.0
   Compiling tftp_client_example v0.1.0 (/home/user/tftpd_client_example)
    Finished dev [unoptimized + debuginfo] target(s) in 8.83s
$ target/debug/tftp_client_example 
thread 'main' panicked at tftp_client_example/src/main.rs:24:6:
called `Result::unwrap()` on an `Err` value: Timeout
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$
```

**Comment by dboycepa** [comment]
(I have a fix for this, but it requires either a change to the upload() API itself or a second public function which takes an unconnected socket and a SocketAddr; this is something you would need to consider.)

**Comment by kiranshila** [comment]
Confirmed, I can reproduce this. I'll push a fix soon. Not sure how I missed this when reading the spec, but of course this is expected behavior that I'm missing.

For future me, here's the relevant bit:
```
   In order to create a connection, each end of the connection chooses a
   TID for itself, to be used for the duration of that connection.  The
   TID's chosen for a connection should be randomly chosen, so that the
   probability that the same number is chosen twice in immediate
   succession is very low.  Every packet has associated with it the two
   TID's of the ends of the connection, the source TID and the
   destination TID.  These TID's are handed to the supporting UDP (or
   other datagram protocol) as the source and destination ports.  A
   requesting host chooses its source TID as described above, and sends
   its initial request to the known TID 69 decimal (105 octal) on the
   serving host.  The response to the request, under normal operation,
   uses a TID chosen by the server as its source TID and the TID chosen
   for the previous message by the requestor as its destination TID.
   The two chosen TID's are then used for the remainder of the transfer.
```

**Comment by kiranshila** [comment]
> ... second public function which takes an unconnected socket and a SocketAddr; this is something you would need to consider

I just went for this, makes more sense anyway (less stateful). I replaced the upload and download functions with this version.

**Comment by kiranshila** [comment]
Thanks again for pointing this out, the two TFTP servers I've been interacting with just kept port 69 on their responses, so I never ran into this.

**Comment by dboycepa** [comment]
I have some more comments on the 0.2.0 version; rather than raise another issue, could I suggest you open a GitHub Discussion for this project?
