### ISSUE TITLE
GitHub's latest released version of tftp_client does not match crate.io's

### ISSUE THREAD

**Issue by dboycepa** [kiranshila/tftp_client#3]
crate.io's view of the latest tftp_client is 0.2.0, and the source code looks correct for 0.2.0.

Unfortunately, the GitHub 'latest release' link shows that it thinks 0.1.0 is the latest; inspecting the code after downloading it from there shoes that it really is the 0.1.0 code (which I guess is consistent!).

Please consider rectifying this.

![image](https://github.com/kiranshila/tftp_client/assets/122276145/485062be-e469-4e56-93d0-ac0751bdb07f)

**Comment by kiranshila** [comment]
I removed the release. crates.io is the source of truth, I do not use github releases (nor do any rust tools afaik). It was published on accident.
